spring.datasource.url=jdbc:h2:mem:b2x2
logging.level.com.zaxxer.hikari=WARN
logging.level.org.apache=WARN
logging.level.org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping=WARN
logging.level.org.springframework.boot.devtools=WARN
logging.level.org.springframework.boot.web.embedded.tomcat=WARN
logging.level.org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext=WARN
logging.level.org.springframework.data.repository.config=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR
server.http2.enabled=true
server.port=443
server.ssl.key-store=classpath:certificates/keystore.p12
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=b2x2
server.ssl.key-store-password=b2x2
spring.jmx.enabled=false
spring.main.banner-mode=off
spring.main.lazy-initialization=true
spring.profiles.active=default
spring.session.timeout=72h
spring.devtools.add-properties=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.web.resources.cache.cachecontrol.cache-public=true
spring.web.resources.cache.cachecontrol.max-age=86400
spring.web.resources.cache.cachecontrol.stale-while-revalidate=86400
spring.web.resources.chain.strategy.content.enabled=true